name = "server"
main = "worker.js"
compatibility_date = "2024-04-03"
account_id = "9ec7cd5f0ffbbf6ac291ee57aae63a4c"

# Any secrets or environment variables should be managed in Cloudflare Dashboard
[vars]
# AUTH_SECRET = "SET_THIS_IN_CLOUDFLARE"
